### ISSUE TITLE
ImportError: No module named kutilities.layers

### ISSUE THREAD

**Issue by XL2248** [DushyantChauhan/EMNLP-19-IIM#1]
from kutilities.layers import AttentionWithContext, Attention, MeanOverTime

can you provide the code of that layers?
or can you provide the code about 'MeanOverTime'?
thanks.

**Comment by GussailRaat** [comment]
Hello,

you can see this link (
http://pydoc.net/keras-utilities/0.1.28/kutilities.layers/) for kutilities.
Plz, let me know if you face any other problem. Thank you.



*Regards,*
Dushyant Singh Chauhan
Ph.D. (CSE)
IIT Patna, India

**Comment by XL2248** [comment]
Thanks.
