### ISSUE TITLE
ValueError: Error when checking target: expected final_output to have 3 dimensions, but got array with shape (169, 3)

### ISSUE THREAD

**Issue by XL2248** [DushyantChauhan/EMNLP-19-IIM#2]
Hello,
There is another issue, please tell me how to address it?
I try to print the shape of 'final_output', which is (?, 3). But why it report a error to need 3 dimensions.
Thanks.

**Comment by GussailRaat** [comment]
Hello,
I used python 2.7 for this code. can you show me the error?

**Comment by XL2248** [comment]
Hello, I also used python 2.7. The details is as follows:
Using TensorFlow backend.
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:08:00.0, compute capability: 7.5

text_audio_video
Traceback (most recent call last):
  File "youTube.py", line 287, in <module>
    CIA_model(mode, filePath, attn_type=attn_type, drops=[drop, drop, rdrop], r_units=r_units, td_units=td_units)
  File "youTube.py", line 265, in CIA_model
    verbose=1)
  File "build/bdist.linux-x86_64/egg/keras/engine/training.py", line 952, in fit
  File "build/bdist.linux-x86_64/egg/keras/engine/training.py", line 789, in _standardize_user_data
  File "build/bdist.linux-x86_64/egg/keras/engine/training_utils.py", line 128, in standardize_input_data
ValueError: Error when checking target: expected final_output to have 3 dimensions, but got array with shape (169, 3)

**Comment by XL2248** [comment]
I used python 2.7, keras 2.2.4 and tensorflow 1.8.0.  
Can you provide some opinions about this?

**Comment by GussailRaat** [comment]
Hello,
I have changed the code a little bit. I think you have commented this line (merged  = MeanOverTime()(merged)). Don't comment this line.

**Comment by GussailRaat** [comment]
Install kutilities and use from kutilities.layers import AttentionWithContext, Attention, MeanOverTime.

**Comment by XL2248** [comment]
Hello, thanks for your reply.
I have tried the new code, where I just change the data path. And I have installed kutilities and use from kutilities.layers import AttentionWithContext, Attention, MeanOverTime. 
But there still is the error above.  And I didn't comment this line, i.e., merged = MeanOverTime().
The error indicates that the target need a 3-D tensor but got a 2-D tensor, which reallly confused me.
Do you have another advice about this?
thanks.

The error:
Using TensorFlow backend.
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:06:00.0, compute capability: 7.5

text_audio_video
Traceback (most recent call last):
  File "youTube_new.py", line 279, in <module>
    CIA_model(mode, filePath, attn_type=attn_type, drops=[drop, drop, rdrop], r_units=r_units, td_units=td_units)
  File "youTube_new.py", line 257, in CIA_model
    verbose=1)
  File "build/bdist.linux-x86_64/egg/keras/engine/training.py", line 952, in fit
  File "build/bdist.linux-x86_64/egg/keras/engine/training.py", line 789, in _standardize_user_data
  File "build/bdist.linux-x86_64/egg/keras/engine/training_utils.py", line 128, in standardize_input_data
ValueError: Error when checking target: expected final_output to have 3 dimensions, but got array with shape (169, 3)

**Comment by XL2248** [comment]
can you provide the version of keras and tf you used? I guess the error may be caused by this.

**Comment by GussailRaat** [comment]
keras: 2.2.2
tensorflow: 1.9.0
